### ISSUE TITLE
Repo Licensing

### ISSUE THREAD

**Issue by matandobr** [devkid/profinet#2]
Hello sir!
Really nice repo, liked it a lot.
Could you specify which license is this code is? 
If I'm not mistaken, 
If a license is not specified, no one can use this code for either open-source/commercial use.
Thanks ahead!

**Comment by alfredkrohmer** [comment]
Like I said in #1, assume [this one](http://www.wtfpl.net).

**Comment by matandobr** [comment]
Great thanks!
